# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1d47c14aa68bd4749693b65459aca63e29415c009580ab36dfb5f0b577dd265370ea2c8394bcdf1494690d172253e3730b1c63cc1a3f9abdfd141f26a3ca190

test:
  secret_key_base: 4dad4b553f836ec9a1e44b61a5deebeb6a3b734768c8a8e30975c72895f0ff7299667110067bb420abb42ae0944e4d52a935db8e181d6fd107426834a2e697a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
